import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [charactor, setCharactor] = useState("");

  const catchCharHandler = (event: React.ChangeEvent<HTMLInputElement>) => {
    const currentValue = event.target.value;
    setCharactor(currentValue);
  };

  const submitValueHandler = (event: React.FormEvent) => {
    event.preventDefault();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>MSW PlayGround</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>For MSW practice</h1>
        <form onSubmit={submitValueHandler}>
          <label></label>
          <input onChange={catchCharHandler} value={charactor} />
          <button></button>
        </form>
      </main>

      <footer className={styles.footer}>footer</footer>
    </div>
  );
};

export default Home;
