import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const MainPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next.js with TypeScript - Open Memo Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Link href={'/memo-list'}>go to MemoList</Link>
    </div>
  );
};

export default MainPage;
